

INSERT INTO `categorias_ocupacionales` (`cod_categorias_ocupacionales`, `descripcion`) VALUES
('01', 'EJECUTIVO'),
('02', 'OBRERO'),
('03', 'EMPLEADO'),
('11', 'FUNCIONARIO '),
('12', 'PROFESIONAL'),
('13', 'TÉCNICO'),
('14', 'AUXILIAR');


INSERT INTO `convenios` (`cod_convenio`, `descripcion`) VALUES
(0, 'NINGUNO'),
(1, 'CANADA'),
(2, 'CHILE'),
(3, 'CAN '),
(4, 'BRASIL');



INSERT INTO `tipos_empleadores` (`id_tipo_empleador`, `descripcion`) VALUES
(1, 'SECTOR PRIVADO'),
(2, 'SECTOR PÚBLICO'),
(3, 'OTRAS ENTIDADES');





INSERT INTO `documentos_vinculos_familiares` (`cod_documento_vinculo_familiar`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'ESCRITURA PÚBLICA', 'ESCRITURA PÚBLICA'),
('02', 'SENTENCIA DE DECLARATORIA DE PATERNIDAD', 'SENT DECLARATORIA DE PATERN'),
('03', 'TESTAMENTO', 'TESTAMENTO'),
('04', 'RESOLUCIÓN DE INCAPACIDAD', 'RESOLUCIÓN DE INCAPACIDAD'),
('05', 'ACTA O PARTIDA DE MATRIMONIO CIVIL', 'ACTA/PARTIDA DE MATRIMONIO CIVIL'),
('06', 'ACTA O PARTIDA DE MATRIMONIO INSCRITO EN REG CONSULAR PERUANO.', 'ACTA/PART MATRIM INSC EN REG CONS PER.'),
('07', 'ACTA O PARTIDA DE MATRIMONIO REALIZADO EN EL EXTERIOR E INSCRITO EN RENIEC O MUNICIPALIDAD. ', 'ACTA/PART MATRIM REALIZ EN EL EXTERIOR '),
('08', 'ESCRITURA PÚBLICA - RECONOC. DE UNIÓN DE HECHO - LEY N.? 29560', 'ESCRIT P?B REC. UNIÓN HECHO LEY 29560'),
('09', 'RESOLUCI?N JUDICIAL - RECONOC. DE UNI?N DE HECHO', 'RESOL JUDICIAL REC. UNIÓN DE HECHO'),
('10', 'ACTA DE NACIMIENTO O DOCUMENTO ANALOGO QUE SUSTENTA FILIACI?N.', 'ACTA NAC/DOC ANALOGO SUST FILIACI?N.'),
('11', 'DECLARACIÓN JURADA EXISTENCIA DE  UNI?N DE HECHO', 'DDJJ EXISTENCIA UNIÓN DE HECHO');


INSERT INTO `modalidades_formativas` (`id_modalidad_formativa`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'APRENDIZAJE CON PREDOMINIO EN LA EMPRESA', 'APRENDIZ. CON PREDOM. EN LA EMPRESA'),
('02', 'APRENDIZAJE CON PREDOMINIO EN EL CFP - PRÁCTICAS P', 'APRENDIZ. CON PREDOM. EN CFP -PRACT PRE'),
('03', 'PR?CTICAS PROFESIONALES', 'PRACTICAS PROFESIONALES'),
('04', 'CAPACITACIÓN LABORAL JUVENIL', 'CAPACITACIÓN LABORAL JUVENIL'),
('05', 'PASANTÍA EN LA EMPRESA', 'PASANT?A EN LA EMPRESA'),
('06', 'PASANTÍA DE DOCENTES Y CATEDRÁTICOS', 'PASANTÍA DE DOCENTES Y CATEDRÁTICOS'),
('07', 'ACTUALIZACIÓN PARA LA REINSERCI?N LABORAL', 'ACTUALIZACIÓN PARA LA REINSERCIÓN LABORA'),
('10', 'SECIGRISTA (1)', 'SECIGRISTA');


INSERT INTO `motivos_bajas_derechohabientes` (`cod_motivo_baja_derechohabiente`, `descripcion`, `descripcion_abreviada`, `condicion`) VALUES
('0', '-', '-', ''),
('02', 'FALLECIMIENTO', 'FALLECIMIENTO', ''),
('03', 'OTROS MOTIVOS NO PREVISTOS', 'OTROS MOTIVOS NO PREVISTOS', ''),
('04', 'DIVORCIO O DISOLUCI?N DE V?NCULO MATRIMONIAL', 'DIVORCIO O DISOL. DE V?NC MATRIM.', ''),
('05', 'FIN DE CONCUBINATO', 'FIN DE CONCUBINATO', ''),
('06', 'FIN DE LA GESTACI', 'FIN DE LA GESTACI', ''),
('07', 'HIJO ADQUIERE MAYOR?A DE EDAD', 'HIJO ADQUIERE MAYOR?A DE EDAD', ''),
('08', 'ERROR EN EL REGISTRO', 'ERROR EN EL REGISTRO', ''),
('09', 'DERECHOHABIENTE ADQUIERE CONDICI?N DE ASEGURADO REGULAR', 'DH ADQUIERE CONDIC DE ASEG REGULAR', '');


INSERT INTO `motivos_bajas_registros` (`cod_motivo_baja_registro`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'RENUNCIA', 'RENUNCIA'),
('02', 'RENUNCIA CON INCENTIVOS', 'RENUNCIA CON INCENTIVOS'),
('03', 'DESPIDO O DESTITUCI', 'DESPIDO O DESTITUCI'),
('04', 'CESE COLECTIVO', 'CESE COLECTIVO'),
('05', 'JUBILACI', 'JUBILACIÓN'),
('06', 'INVALIDEZ ABSOLUTA PERMANENTE', 'INVALIDEZ ABSOLUTA PERMAN'),
('07', 'TERMINACIÓN DE LA OBRA O SERVICIO, CUMPLIMIENTO CONDICIÓN RESOLUTORIA O VENCIMIENTO DEL PLAZO', 'TERMIN OBRA/SERV, CUMPLIM CONDIC RESOL. O VENC PLAZO'),
('08', 'MUTUO DISENSO', 'MUTUO DISENSO'),
('09', 'FALLECIMIENTO', 'FALLECIMIENTO'),
('10', 'SUSPENSIÓN DE LA PENSIÓN (1)', 'SUSPENSIÓN DE LA PENSI'),
('11', 'REASIGNACIÓN SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA(2)', 'REASIGNACIÓN'),
('12', 'PERMUTA SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA (2)', 'PERMUTA'),
('13', 'TRANSFERENCIA SERVIDOR DE LA ADMINISTRACIÓN PÚBLICA (2)', 'TRANSFERENCIA'),
('14', 'BAJA POR SUCESIÓN EN POSICIÓN DEL EMPLEADOR', 'BAJA POR SUC. EN POSIC DEL EMPLEADOR'),
('15', 'EXTINCI?N O LIQUIDACIÓN DEL EMPLEADOR', 'EXTINCIÓN O LIQUID. DEL EMPLEADOR'),
('16', 'OTROS MOTIVOS DE CADUCIDAD DE LA PENSI?N (1)', 'OTR MOTIV CADUC PENSIÓN '),
('17', 'NO SE INICIÓ LA RELACIÓN LABORAL O PRESTACIÓN EFECTIVA DE SERVICIOS', 'NO SE INICIÓ LA REL.  LABORAL O PREST. DE SERVICIOS');


INSERT INTO `niveles_educativos` (`cod_nivel_educativo`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'SIN EDUCACI?N FORMAL', 'SIN EDUCACI?N FORMAL'),
('02', 'EDUCACI?N ESPECIAL INCOMPLETA', 'ESPECIAL INCOMPLETA'),
('03', 'EDUCACI?N ESPECIAL COMPLETA', 'ESPECIAL COMPLETA'),
('04', 'EDUCACI?N PRIMARIA INCOMPLETA', 'PRIMARIA INCOMPLETA'),
('05', 'EDUCACI?N PRIMARIA COMPLETA', 'PRIMARIA COMPLETA'),
('06', 'EDUCACI?N SECUNDARIA INCOMPLETA', 'SECUNDARIA INCOMPLETA'),
('07', 'EDUCACI?N SECUNDARIA COMPLETA', 'SECUNDARIA COMPLETA'),
('08', 'EDUCACI?N T?CNICA INCOMPLETA', 'T?CNICA INCOMPLETA'),
('09', 'EDUCACI?N T?CNICA COMPLETA', 'T?CNICA COMPLETA'),
('10', 'EDUCACI?N SUPERIOR (INSTITUTO SUPERIOR, ETC) INCOM', 'SUPERIOR INCOMPLETA (INSTIT. SUPER)'),
('11', 'EDUCACI?N SUPERIOR (INSTITUTO SUPERIOR, ETC) COMPL', 'SUPERIOR COMPLETA  (INSTIT SUPER)'),
('12', 'EDUCACI?N UNIVERSITARIA INCOMPLETA', 'UNIVERSITARIA INCOMPLETA'),
('13', 'EDUCACI?N UNIVERSITARIA COMPLETA', 'UNIVERSITARIA COMPLETA'),
('14', 'GRADO DE BACHILLER', 'GRADO DE BACHILLER'),
('15', 'TITULADO', 'TITULADO'),
('16', 'ESTUDIOS DE MAESTR?A INCOMPLETA', 'ESTUD. MAESTR?A INCOMPLETA'),
('17', 'ESTUDIOS DE MAESTR?A COMPLETA', 'ESTUD. MAESTR?A COMPLETA'),
('18', 'GRADO DE MAESTR?A', 'GRADO DE MAESTR?A'),
('19', 'ESTUDIOS DE DOCTORADO INCOMPLETO', 'ESTUD. DOCTORADO INCOMPLETO'),
('20', 'ESTUDIOS DE DOCTORADO COMPLETO', 'ESTUD. DOCTORADO COMPLETO'),
('21', 'GRADO DE DOCTOR', 'GRADO DE DOCTOR');


INSERT INTO `regimenes_aseguramientos_salud` (`cod_regimen_aseguramiento_salud`, `descripcion`, `descripcion_abreviada`) VALUES
('00', 'ESSALUD REGULAR (Exclusivamente)', 'ESSALUD REGULAR '),
('01', 'ESSALUD REGULAR Y EPS/SERV. PROPIOS', 'ESSALUD REGULAR Y EPS/SERV. PROP.'),
('02', 'ESSALUD TRABAJADORES PESQUEROS', 'ESSALUD TRAB PESQUEROS'),
('03', 'ESSALUD TRABAJADORES PESQUEROS Y EPS(SERV.PROPIOS)', 'ESSALUD TRAB PESQ Y EPS(SERV.PROP)'),
('04', 'ESSALUD AGRARIO/ACU?COLA', 'ESSALUD AGRARIO/ACU?COLA'),
('05', 'ESSALUD PENSIONISTAS', 'ESSALUD PENSIONISTAS'),
('20', 'SANIDAD DE FFAA Y POLICIALES (1)', 'SANIDAD FFAA Y POLICIALES (1)'),
('21', 'SIS ? MICROEMPRESA(2)', 'SIS ? MICROEMPRESA (2)');



INSERT INTO `regimenes_laborales` (`cod_regimen_laboral`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'PRIVADO GENERAL -DECRETO LEGISLATIVO N.? 728', 'D LEG N.? 728'),
('02', 'P?BLICO GENERAL - DECRETO LEGISLATIVO N.? 276', 'D.LEG N.? 276'),
('03', 'PROFESORADO - LEY N.? 24029', 'PROFESORADO LEY 24029'),
('04', 'MAGISTERIO - LEY N.? 29062', 'MAGISTERIO  LEY 29062'),
('05', 'DOCENTES UNIVERSITARIOS - LEY N.? 23733', 'DOC UNIVERS LEY 23733'),
('06', 'PROFESIONALES DE LA SALUD LEY N.? 23536', 'PROFES SALUD LEY 23536'),
('07', 'TECNICOS Y AUXILIARES ASIST. DE LA SALUD - LEY N.? 28561', 'TECN Y AUX ASIST SALUD LEY 28561'),
('08', 'SERUM - LEY N.? 23330', 'SERUM LEY 23330'),
('09', 'JUECES - CARRERA JUDICIAL - LEY N.? 29277', 'JUECES LEY 29277'),
('10', 'FISCALES - D. LEG.  N.? 052', 'FISCALES D.LEG 052'),
('11', 'SERVICIO DIPLOM?TICO DE LA REP?BLICA - LEY N.? 28091', 'SERVICIO DIPLOM. REP?BLICA LEY 28091'),
('12', 'MILITARES', 'MILITARES'),
('13', 'POLICIA NACIONAL DEL PER? - LEY N.? 27238', 'POLICIAS LEY 27238'),
('14', 'ESPECIAL GER. P?BLICOS DECRETO LEGISLATIVO N.? 1024 (2)', 'ESPECIAL GER. P?BL D LEG 1024'),
('15', 'CONTRATO ADMINISTRATIVO DE SERVICIOS - D.LEG. N.? 1057', 'CAS D.LEG 1057'),
('16', 'MICROEMPRESA D. LEG. 1086 (1)', 'MICROEMPRESA'),
('17', 'PEQUE?A EMPRESA D. LEG. 1086 (1)', 'PEQUE?A EMPRESA'),
('18', 'AGRARIO LEY 27360', 'AGRARIO'),
('19', 'EXPORTACION NO TRADICIONAL D. LEY 22342', 'EXPORTACION NO TRADICIONAL'),
('20', 'MINEROS', 'MINEROS'),
('21', 'CONSTRUCCION CIVIL', 'CONSTRUCCION CIVIL'),
('99', 'OTROS NO PREVISTOS', 'OTROS');


INSERT INTO `regimenes_pensionarios` (`cod_regimen_pensionario`, `descripcion`, `descripcion_abreviada`) VALUES
('02', 'DECRETO LEY 19990 - SISTEMA NACIONAL DE PENSIONES - ONP', 'DL 19990 - SIST NAC DE PENS - ONP'),
('03', 'DECRETO LEY 20530 ', 'DECRETO LEY 20530'),
('09', 'CAJA DE BENEFICIOS DE SEGURIDAD SOCIAL DEL PESCADOR', 'CBSSP'),
('10', 'CAJA DE PENSIONES MILITAR ', 'CAJA DE PENSIONES MILITAR '),
('11', 'CAJA DE PENSIONES POLICIAL', 'CAJA DE PENSIONES POLICIAL'),
('12', 'OTROS REGIMENES PENSIONARIOS (1)', 'OTROS REGIMENES PENSIONARIOS'),
('13', 'RÉGIMEN DEL SERVICIO DIPLOMÁTICO DE LA REPÚBLICA ', 'REGIMEN DEL SDR '),
('21', 'SPP INTEGRA', 'SPP INTEGRA'),
('22', 'SPP HORIZONTE', 'SPP HORIZONTE'),
('23', 'SPP PROFUTURO', 'SPP PROFUTURO'),
('24', 'SPP PRIMA', 'SPP PRIMA'),
('99', 'SIN REGIMEN PENSIONARIO', 'SIN REGIMEN PENSIONARIO');


INSERT INTO `situaciones` (`cod_situacion`, `descripcion`, `descripcion_abreviada`) VALUES
('0', 'BAJA (1)', 'BAJA'),
('1', 'ACTIVO O SUBSIDIADO (1)', 'ACTIVO O SUBSIDIADO'),
('2', 'SIN VÍNCULO LABORAL CON CONCEPTOS PENDIENTE DE LIQUIDAR  (2)', 'SIN VINC. LAB. CON CONC PEND POR LIQUIDA'),
('3', 'SUSPENSIÓN PERFECTA DE LABORES (3)', 'SUSPENSIÓN PERFECTA DE LABORES');



INSERT INTO `telefonos_codigos_nacionales` (`cod_telefono_codigo_nacional`, `descripcion`) VALUES
('0', '-'),
('1', 'LIMA Y CALLAO'),
('41', 'AMAZONAS'),
('42', 'SAN MARTIN'),
('43', 'ANCASH'),
('44', 'LA LIBERTAD'),
('51', 'PUNO'),
('52', 'TACNA'),
('53', 'MOQUEGUA'),
('54', 'AREQUIPA'),
('56', 'ICA'),
('61', 'UCAYALI'),
('62', 'HUANUCO'),
('63', 'PASCO'),
('64', 'JUNIN'),
('65', 'LORETO'),
('66', 'AYACUCHO'),
('67', 'HUANCAVELICA'),
('72', 'TUMBES'),
('73', 'PIURA'),
('74', 'LAMBAYEQUE'),
('76', 'CAJAMARCA'),
('82', 'MADRE DE DIOS'),
('83', 'APURIMAC'),
('84', 'CUSCO'),
('94', 'LA LIBERTAD'),
('95', 'AREQUIPA'),
('96', 'PIURA'),
('97', 'LAMBAYEQUE');


INSERT INTO `tipos_comprobantes_pagos` (`cod_tipo_comprobante_pago`, `descripcion`) VALUES
('R', 'RECIBO POR HONORARIOS'),
('N', 'NOTA DE CR?DITO'),
('D', 'DIETA'),
('O', 'OTRO COMPROBANTE');


INSERT INTO `tipos_contratos` (`cod_tipo_contrato`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'A PLAZO INDETERMINADO - D.LEG. 728', 'A PLAZO INDET - D.LEG. 728'),
('02', 'A TIEMPO PARCIAL', 'A TIEMPO PARCIAL'),
('03', 'POR INICIO O INCREMENTO DE ACTIVIDAD', 'POR INICIO O INCREM DE ACTIV'),
('04', 'POR NECESIDADES DEL MERCADO', 'POR NECES DEL MERCADO'),
('05', 'POR RECONVERSIÓN EMPRESARIAL', 'POR RECONV EMPRESARIAL'),
('06', 'OCASIONAL', 'OCASIONAL'),
('07', 'DE SUPLENCIA', 'DE SUPLENCIA'),
('08', 'DE EMERGENCIA', 'DE EMERGENCIA'),
('09', 'PARA OBRA DETERMINADA O SERVICIO ESPECÍFICO', 'OBRA DETERM O SERV ESPEC'),
('10', 'INTERMITENTE', 'INTERMITENTE'),
('11', 'DE TEMPORADA', 'DE TEMPORADA'),
('12', 'DE EXPORTACI?N NO TRADICIONAL D.LEY 22342', 'DE EXPORT. NO TRADIC.'),
('13', 'DE EXTRANJERO - D.LEG.689', 'DE EXTRANJERO - D.LEG. 689'),
('14', 'ADMINISTRATIVO DE SERVICIOS - D.LEG 1057 (1)', 'CAS  - D.LEG 1057'),
('15', 'NOMBRADO - D.LEG. N.° 276 (1)', 'NOMBRADO - D.LEG. N.° 276 (1)'),
('16', 'SERVICIOS PERSONALES  - APLICABLES A LOS REGÍM. DE CARRERA (1)', 'SERV. PERS  - REGÍM. DE CARRERA (1)'),
('17', 'GERENTE PÚBLICO - D.LEG. 1024 (1)', 'GERENTE P?BLICO - DL 1024'),
('18', 'A DOMICILIO', 'A DOMICILIO'),
('19', 'FUTBOLISTAS PROFESIONALES', 'FUTBOLISTAS PROFESIONALES'),
('20', 'AGRARIO - LEY 27360', 'AGRARIO - LEY 27360'),
('21', 'MIGRANTE ANDINO DECISI?N 545', 'MIGRANTE ANDINO '),
('99', 'OTROS NO PREVISTOS', 'OTROS NO PREVISTOS');


INSERT INTO `tipos_documentos` (`cod_tipo_documento`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'DOCUMENTO  NACIONAL DE IDENTIDAD', 'DNI'),
('04', 'CARNE DE EXTRANJERIA', 'CARNE EXT.'),
('06', 'REG. UNICO DE CONTRIBUYENTES (1)', 'RUC'),
('07', 'PASAPORTE', 'PASAPORTE'),
('11', 'PARTIDA DE NACIMIENTO (2)', 'PART. NAC.');


INSERT INTO `tipos_pagos` (`cod_tipo_pago`, `descripcion`) VALUES
('1', 'EFECTIVO'),
('2', 'DEPÓSITO EN CUENTA'),
('3', 'OTROS');


INSERT INTO `tipos_suspensiones_relaciones_laborales` (`cod_tipo_suspen_relacion_laboral`, `descripcion`, `descripcion_abreviada`) VALUES
('01', 'S.P. SANCI?N DISCIPLINARIA', 'S.P. SANCI?N DISCIPLINARIA'),
('02', 'S.P. EJERCICIO DEL DERECHO DE HUELGA', 'S.P. EJERCICIO DERECHO HUELGA'),
('03', 'S.P. DETENCI?N DEL TRABAJADOR, SALVO EL CASO DE CONDENA PRIVATIVA DE LA LIBERTAD', 'S.P. DETENCI?N DEL TRABAJADOR'),
('04', 'S.P. INHABILITACI?N ADMINISTRATIVA O JUDICIAL POR PER?ODO NO SUPERIOR A TRES MESES', 'S.P. INHABILITACI?N ADMINISTRATIVA O JUDICIAL'),
('05', 'S.P. PERMISO O LICENCIA CONCEDIDOS POR EL EMPLEADOR SIN GOCE DE HABER', 'S.P. PERMISO O LICENCIA SIN GOCE DE HABER'),
('06', 'S.P. CASO FORTUITO O FUERZA MAYOR', 'S.P. CASO FORTUITO O FUERZA MAYOR'),
('07', 'S.P. FALTA NO JUSTIFICADA', 'S.P. FALTA NO JUSTIFICADA'),
('08', 'S.P. POR TEMPORADA O INTERMITENTE', 'S.P. POR TEMPORADA O INTERMITENTE'),
('20', 'S.I. ENFERMEDAD O ACCIDENTE (PRIMEROS VEINTE D?AS)', 'S.I. ENFERM/ACCIDENTE (20 PRIMEROS D?AS)'),
('21', 'S.I. INCAPACIDAD TEMPORAL (INVALIDEZ, ENFERMEDAD Y ACCIDENTES)', 'S.I. INCAP TEMPORAL (SUBSIDIADO))'),
('22', 'S.I. MATERNIDAD DURANTE EL DESCANSO PRE Y POST NATAL', 'S.I. MATERNIDAD - PRE Y POST NATAL'),
('23', 'S.I. DESCANSO VACACIONAL', 'S.I. DESCANSO VACACIONAL'),
('24', 'S.I. LICENCIA PARA DESEMPE?AR CARGO C?VICO Y PARA CUMPLIR CON EL SERVICIO MILITAR OBLIGATORIO', 'S.I. LIC  DESEMP CARGO C?VICO Y PARA SMO'),
('25', 'S.I. PERMISO Y LICENCIA PARA EL DESEMPE?O DE CARGOS SINDICALES', 'S.I. LIC DESEMPE?O CARGOS SINDICALES'),
('26', 'S.I. LICENCIA CON GOCE DE HABER', 'S.I. LICENCIA CON GOCE DE HABER'),
('27', 'S.I. D?AS COMPENSADOS POR HORAS TRABAJADAS EN SOBRETIEMPO', 'S.I. D?AS COMPENS POR HORAS DE SOBRETIEMPO'),
('28', 'S.I. D?AS LICENCIA POR PATERNIDAD', 'S.I. D?AS LICENCIA POR PATERNIDAD'),
('29', 'S.I. DIAS LICENCIA POR ADOPCI?N ', 'S.I. DIAS LICENCIA POR ADOPCI?N ');


INSERT INTO `tipos_trabajadores` (`cod_tipo_trabajador`, `descripcion`, `descripcion_abreviada`) VALUES
('19', 'EJECUTIVO', 'EJECUTIVO'),
('20', 'OBRERO', 'OBRERO'),
('21', 'EMPLEADO', 'EMPLEADO'),
('22', 'TRABAJADOR PORTUARIO - LEY 27866', 'TRAB.PORTUARIO'),
('23', 'PRACTICANTE SENATI - DEC. LEY 20151', 'PRACT. SENATI'),
('24', 'PENSIONISTA O CESANTE', 'PENSIONISTA O CESANTE'),
('26', 'PENSIONISTA - LEY 28320', 'PENSIONISTA - LEY 28320'),
('27', 'CONSTRUCCI?N CIVIL', 'CONSTRUCCI?N CIVIL'),
('28', 'PILOTO Y COPILOTO DE AVIACI?N COMERCIAL', 'PILOTO Y COPIL DE AVIA. COM.'),
('29', 'MAR?TIMO, FLUVIAL O LACUSTRE', 'MAR?T, FLUVIAL O LACUSTRE'),
('30', 'PERIODISTA', 'PERIODISTA'),
('31', 'TRABAJADOR DE LA INDUSTRIA DE CUERO', 'TRAB. DE LA IND. DE CUERO'),
('32', 'MINERO DE MINA DE SOCAV', 'MINERO DE SOCAV'),
('36', 'PESCADOR - LEY 28320', 'PESCADOR - LEY 28320'),
('37', 'MINERO DE TAJO ABIERTO', 'MINERO DE TAJO ABIERTO'),
('38', 'MINERO DE INDUSTRIA MINERA METAL?RGICA', 'MINERO IND. MINERA METAL.'),
('56', 'ARTISTA -  LEY 28131', 'ARTISTA -  LEY 28131'),
('64', 'AGRARIO DEPENDIENTE - LEY 27360', 'AGRARIO DEPEND.- LEY 27360'),
('65', 'TRABAJADOR ACTIVIDAD ACU?COLA - LEY 27460', 'TRAB. ACTIV.ACU?COLA LEY 27460'),
('66', 'PESCADOR Y PROCESADOR ARTESANAL INDEPENDIENTE  - LEY 27177 ', 'PESC.Y PROC.ARTES.INDEP.'),
('67', 'REGIMEN  ESPECIAL D. LEG.1057 - CAS', 'REG. ESPECIAL D. LEG.1057 - CAS'),
('71', 'CONDUCTOR DE MICROEMPRESA REMYPE - D.LEG.1086', 'CONDUCT MICROEMP.REMYPE D.L.1086'),
('82', 'FUNCIONARIO P?BLICO', 'FUNCIONARIO P?BLICO'),
('83', 'EMPLEADO DE CONFIANZA', 'EMPLEADO DE CONFIANZA'),
('84', 'SERVIDOR P?BLICO - DIRECTIVO  SUPERIOR', 'SERVIDOR P?B - DIRECT SUPERIOR'),
('85', 'SERVIDOR P?BLICO - EJECUTIVO', 'SERVIDOR P?B - EJECUTIVO'),
('86', 'SERVIDOR P?BLICO - ESPECIALISTA', 'SERVIDOR P?B - ESPECIALISTA'),
('87', 'SERVIDOR P?BLICO - DE APOYO', 'SERVIDOR P?B - DE APOYO'),
('88', 'PERSONAL DE LA ADMIN. P?BLICA - ASIGNACI?N ESPECIAL - D.U. 126-2001', 'PERS ADM P?B - ASIG ESP DU 126-2001'),
('89', 'PERSONAL DE LAS FUERZAS ARMADAS Y POLICIALES (1)', 'PERS DE LAS FFAA Y POLICIALES'),
('90', 'GERENTES P?BLICOS  - D. LEG. 1024', 'GERENTES P?B.  - D.LEG 1024'),
('91', 'MIIEMBROS DE OTROS REG. ESPECIALES DEL SECTOR P?BLICO', 'MIIEMBROS DE OTROS REG. ESPEC S.PUBLICO'),
('98', 'PERSONA QUE GENERA INGRESOS DE CUARTA - QUINTA CATEGOR?A', 'CUARTA - QUINTA CATEGOR?A');


INSERT INTO `vias` (`cod_via`, `descripcion`) VALUES
('01', 'AVENIDA'),
('02', 'JIRÓN'),
('03', 'CALLE'),
('04', 'PASAJE'),
('05', 'ALAMEDA'),
('06', 'MALECÓN'),
('07', 'OVALO'),
('08', 'PARQUE'),
('09', 'PLAZA'),
('10', 'CARRETERA'),
('13', 'TROCHA'),
('14', 'CAMINO RURAL'),
('15', 'BAJADA'),
('16', 'GALERIA'),
('17', 'PROLONGACIÓN'),
('18', 'PASEO'),
('19', 'PLAZUELA'),
('20', 'PORTAL'),
('21', 'CAMINO AFIRMADO'),
('22', 'TROCHA CARROZABLE'),
('99', 'OTROS');


INSERT INTO `vinculos_familiares` (`cod_vinculo_familiar`, `descripcion`, `descripcion_abreviada`) VALUES
('02', 'CÓNYUGE', 'C?NYUGE'),
('03', 'CONCUBINA(O)', 'CONCUBINA(O)'),
('04', 'GESTANTE', 'GESTANTE'),
('05', 'HIJO MENOR DE EDAD', 'HIJO MENOR DE EDAD'),
('06', 'HIJO MAYOR DE EDAD INCAPACITADO PERMANENTE', 'HIJO MAYOR EDAD INCAP PERM');


INSERT INTO `zonas` (`cod_zona`, `descripcion`) VALUES
('01', 'URB. URBANIZACIÓN'),
('02', 'P.J. PUEBLO JOVEN'),
('03', 'U.V. UNIDAD VECINAL'),
('04', 'C.H. CONJUNTO HABITACIONAL'),
('05', 'A.H. ASENTAMIENTO HUMANO'),
('06', 'COO. COOPERATIVA'),
('07', 'RES. RESIDENCIAL'),
('08', 'Z.I. ZONA INDUSTRIAL'),
('09', 'GRU. GRUPO'),
('10', 'CAS. CASERÍO'),
('11', 'FND. FUNDO'),
('99', 'OTROS');


INSERT INTO `estados_civiles` (`id_estado_civil`, `descripcion`) VALUES
(1, 'SOLTERO'),
(2, 'CASADO');


INSERT INTO `tipos_sociedades_comerciales` (`id_tipo_sociedad_comercial`, `descripcion`, `descripcion_abreviada`) VALUES
(1, 'SOCIEDAD ANONIMA', 'S.A.'),
(2, 'SOCIEDAD ANONIMA CERRADA', 'S.A.C.');

INSERT INTO `montos_remuneraciones` (`id_monto_remuneracion`, `cantidad`, `fecha_creacion`) VALUES
(1, '650.00', NULL),
(2, '780.00', NULL);
